language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "v3UNt9BYe9OVB6+0lfdBlNobK/GetI++4mu/xbqy05tdwPZt3OiIZ2pUCsaa/x7Z+J3b9G2VJ9gYPJDXAW9zCNwfuiC0vqND45FIbOIJIwNg90a3HWEcUU8kN8983dF6eFX8bnPImyl5Q0nv+DTuC+o5BW8vDbTZcClEeDU13MH79jZ6+gId2zIkpy+NVmoPFgRF9ydIq9cfS5I/xVscQ3rTXjt2eQOOgIJUUcmEgteDfMeD9nFjd8cSBt2ZmiWbq01AQOnhYyfEwX3CozBZVLNUrkQGqsUVJYmBzKxVi6vru/kPGijWlEM4qxBwsyVlEPqQL/4iPiz7n30xfJe5uPINPAKXZmZxbChj3WT5HJgJXoVl8KINC5P3hAFqVbkDOlWzKm0CYG17V1stWe39rTbu0AY2O+14F7xD0nkaYwLW9uHnOCOX3ILYrQlktFR6TLlS3bU5HlF2yNRKQp15NJd/s1oVwzshf+bBdqbr1P6xfXejZzjw2O1uXMhuJoeK5BGo+lRKqMbWdN+QXOaoeUmSoyjqhxW/Rmtb/d+kkUtqsBE2IOd+ZfnztxvSInjR8jCBRFDUpFgS/XruxazChap48pBaqLP7Pg+Tz7agAhXs3f7+wW9YpYGC1401CMSrihlZqtv8GuL7SuE/u1rlujqTJHYLrFtjaXsLPflKaLM="
  - secure: "OlyjkWp5FHUq8cipdrMrmg9Ltz6E1H6SQeK7D7Ijs2uV0kMX7tf0ZMn3RzOc0xStQQQ+IrjClcVXmORt/gkMKwHr9APQrlTbT4fH9Za54XR2YD+J9HOVbfFwa0B782+HMwkC6I+8uKRS7zf3DNGXd85gZ2PvzYibABZAH08n2RgkBOg+xrI/DRLvvp3SrhWp68dMpVnfjAiom0mCDc8x9yx70HXh/n7MOrzHShe7bL8yN7XSIDZ1hcc32yrqkLf8O39aFElYJOZ9aQmI2JrrBAYBY6AtJmm2hEOCWxWCb9ZSvhiXWMJwmx+bSxBFVI0OcPmtGOdaPc0CzbK6QXSI0mZPMeFFPtwnyCuNDTAzJBKvIAN/uiHxC2zasp4nwps2mA+1qNwnvtjDwzG5288r3Gt9FdeJxJPB9eMZvyjzzEyMvcatgNYs00RNKR68S8dx6nCj4JjNeEyrVESZxcmZcr0jCIwozdM79d7EPTRCRPUMX+P3vSAC2ezPjh5t43cyweSNnidmYeEt34rYrDq23yiEM1aXDweuaz7w2zkjcivKTF5BfS2pY1bQSqnFogtqtr/PVq3NmNPCWxoyAR5DZq2hSKuZ1c+MTfVzWTei/BhIgH/obxondY6ec2U0dTGf8x9GAWqn13wAulxap8rmT2mn8FSf5rewJnSJMi+mRuk="
  - secure: "C0MGpWAhombOobRB8SfWJ5kYXPo/h+rbVNrzBcUU7JMaIZyZmn/O2uUubWgDuxCPL8Gt93gYnXN3clzx4A2uV6gar3iRH6GOThhxEvvvA3Mx0gegtmDAP47SL1XRglPEuC+ejMe6j8UWV4+zCvPGXUUR1ZFkdS/YMzEKkK3pGOGY76g75+FT0N/2xRlkb+z97ZuTFNDZny8utgrV9eoD0cxzEjJgSO+aB5BG2T7E9At8W0vgjGhYdPG/QrRbDJhO1K6r2EO0dq09FnQS470FdM5SZQRiJgxXPbmqpJSvPF4UjiqtzcDeaPMFuJT4ApLN7/n1hOIrJfNfkc1w3Jmdmx9/yBH0GXfYFMfa9D+YYxza4U35SojfG7RFac80JKDoEDNSAbbjmDe2G1+pFZE9Wa6h6C311llDO8wOSOwKNt3MkPXmYDEocII7d2uNYCe0YqUDywbwAJrURWm1r/TDZm977mN3y1fz0xdQtjrVjAEbiNYUIEPTWhrAI+dOlm/VcjXA/8KNcFJg5PYh+7SMVBr/8e6BNdWfRrAM1akZZrl/To01Mf6L/8r2Q1KEKRyxB44i8NT2tmwzsMAMWBpZrTi6RXw6umxhyLrCbBmJ+rgHEcgN3ZZpY3U2kde1TFxy3RwnOQlf0nUeLLa7JkiPACYJC4nateEi6uvhF64yJBA="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_08f14242a184_key -iv $encrypted_08f14242a184_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi