language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: Jk+42wmsFd16eGkZcycgkRb40TguSK0SQa0gv9pT+FW9hO2i9Nbzv+OEsl9dFr6zIYkGJw2pHtfAPVmqscsjlL9UMLkjxD6EO5ACPwKfjvUGKdkbKnE36NPsUeSMU26jeH37YtKWtWjyotVdSluCO08DUqDf2Ff6WpDS0MjqhqWxgDSu70bY7KcGO9qj2du4XV2N28KiaK9ckyebqNmgViwz3Huxz1Kk3AwcTiDNR+sMSNTUywv5935AneVlKmreBuzAIg38dFcjjiq9GZdW//z9i07vgq3rqoYhhm8A3YKKUZu2xJaTdtXMUed+S9O02EnFwAUTUOAhUnwawMlgUut5e49WUm1LEf+UyoxGc4aVSg+Tb/9hg9Eq2gkuSbe8Qhjz0xeCdBPbvQ+lgwZf+vFqcjUeuY+EttF6yGZPdis3BbjLecglAFyq/0VDH6oypOzTDqbtnSiJr/tg5LVJP8doW5u28M+7PXq5LRU503jv2hme3WwbPNvKOVH8mfZXVTI4cEUKkvpCMtjQ0K4aUgZdkILskEkSUiQ+ITlZ9fnyDcmMR9sWHUrL/qfu/zfo+VBQH3tF5zwLALlWt9G5tgzoISStf+ckkm6+7m87IE6cze6ojP2zbfcTlaWz5xwk/HIqwmwN5lqd8sg3ur24+3MpustP3+sg+I+sJUayNsM=
  - secure: sfzFX1gBNSiYddZmZM/XDyii3CaP36q+fU7KkWHh3OcgkJwG09nXSV1Sb7PR9qdbDqIXGLVPqNBUWDmJUXrk7mBdaUkSm5RZ4VQL/TyOq6vVUfx8GF7PdydJML+giDk393pcFH0nJhyw/78sBzv34M94a0sbWlWTaaI15hdOKUVDGdork82husb+CQ2KdOTqV4K8AGZ55jQHU3GMdQlcQxkIL0KUyE9flUxLGT1f+kOXZtP/5zWwDSae9EZs61ff6V5EE2Qgv/hkMvFELxkzSNnmlnWe9kAVhjI2YLsSkf1QC1SlxS0665eBn0a//ylL9zMk9q5rClERr4a2pMXgJ+UPtsVn3Sw3BI+vQrYffVsJcxskG2oVUgpsLaY9hLcFjUEy9mT536/oxrZ/Wt4c145Xeaz4DBsougDmFS90TOlVsyisVzXEgPBcGrfGbW5ISTYKRy15ANiJyTKtqgKkE3WSEZ9U+P6EqtjmfVXGvManEfkTJTlfV0b0OqfmkOJfq88PzjM4AT+MHd6Z41FTadzefz7/3XZjss2J+EqUpEEFR1IA1oN+aU8iaolrodNE+5SUEta6YscA1+qzb2nkT9o4aq+37CJqIST84Z2WyCO2cevs3HJ77Bm8ozMwOAmcA4TQ6gAoetiYeiimBwgORfAGVTFeIOqzJXVXCFy0N0E=
  - secure: zCBgg6h6L4s03ZlPE7xd3nOA2+CH83v0g1NlYUdIG33G811PIh+2DRh4RXZ9X604dMVbJDxdtXFGIxZ5bEtYHevx9cYkwEzhrCgYPEpKXhcTmWhmCQmgMeUwlfx8nYJI6NUh0XVUQy2dIe/spiOheau44Opi8v6IqaCARs0zR+mYLoMxF9eOYX3vYZWRxc9/dWFsc/dWb+D4eW0TyCDa2PMmn/oXgP9txYPcjkl541WgH8Uhz/DJUxc6AQNYdxPU1SpDZ2GYSKRQqj663AXdlLUzjCRrIBkI4w8fz7EYacu+nf12su4bX3lTLnvT8Ol2jXUvtL3LJn3IXpjNv3ioBcJo4m3f3KdB4F1cgqEOTI1MOZWlFr35PnvT6D2yhazMKZzTseRaAL+oUzlfoJTWJdz5ybOwVytUuMNPA73iZwL/pUkI8RetQ6oDoc7SRTjfd0BioNTRL82hwns7xaCqoj8XN5NErzG22dTWhBVFxxdGZpL9USXs+un602lmrs/88Vsoz3R3eEkIwW3trp3TvUStiavwCa2vFdD3dbuJDEVSCnNunyVyXzPCOVRSd9j2V9z/vdbmu4JMcXjVPV5OhCW0zPItDK6beKSKNujY/m4lo1g7osAU0U2QZq8H4G3hgp+Lhghie5FH23zU1433VqTg9oJTlw86fX4D1UN73V0=

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_08f14242a184_key -iv $encrypted_08f14242a184_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi